### PR TITLE
Resolving Issue 78 and 80 by fixing broken links to assets and images…

### PR DESCRIPTION
**Pull request by kateefly**
… on the Environmental Scan page

@akhtars is this something you would be able to review? Please let me know if it's not.

### CODE REVIEW

**Comment by akhtars** [comment]
Yes, will do, thanks!

**Comment by akhtars** [comment]
The link and asset updates function as expected.

@kateefly the only question I have is on page 12 of the added PDF, it looks like some terminal commands ended up in the text of the contributors list. If this is part of the original document and we're okay with proceeding as-is, I'll merge, but wanted to double-check in case there's an available version of the PDF that fixes this.

**Comment by kateefly** [comment]
Unfortunately that's the only copy we have. It's not pretty but I think it's ok - it's not blocking any information from being shown.

**Comment by akhtars** [comment]
Understood, thanks!

**Pull request merged**
