### PR TITLE
Updated Metadata Benchmarks project page

### PR DESCRIPTION
**Pull request by kateefly**

### CODE REVIEW

**Comment by kateefly** [comment]
Not sure why the conflicts exists - here's what I suggest (use the web editor link to make changes):

In Gemfile.lock, keep lines 212-216 and 232. Delete lines 211, 217-223, 233-235. The resulting code should look like this:
image

In benchmarks.md, delete 28, 31-34 and keep lines 29-30. The resulting code should look like this:
image

**Comment by aneatrour** [comment]
Hi Kate - I'm not sure if I need to do something special about the conflicts with the Gemfile.lock?

**Comment by aneatrour** [comment]
Hi Kate, I think I got it, thanks for your help working through the issues!

**Comment by kateefly** [comment]
Glad it worked! Sorry I wasn't responsive before but it looks like everything worked out. I'll close the ticket as well.

**Pull request merged**
