### PR TITLE
Updated Benchmarks page with white paper added

### PR DESCRIPTION
**Pull request by kateefly**
@aneatrour if you have bandwidth, could you review? If not, let me know and I'll add someone else. :)

### CODE REVIEW

**Comment by kateefly** [comment]
Removing Anna as the requested reviewer as she's out. @plampron2 are you able to review?

**Comment by plampron2** [comment]
yes! Might take a minute to remember how to do this :)

**Comment by plampron2** [comment]
@kateefly lines 43 and 48 don't have a line break when I look at the page in jekyll. 
ex: Rachel Wittmann, Digital Curation Librarian Marriott Library, University of Utah rachel.wittmann@utah.edu

Let me know if you want to fix it or if I should merge as is.

**Comment by kateefly** [comment]
Thanks for the catch! I just uploaded an update that I hope should take care of this. Could you pull down the updated page and see if it looks ok?

**Pull request merged**
